no_of_videos: 3
randomize: false
video_list: 'test_videos.json'
resolutions: ['360p','480p','720p HD','1080p HD']

driver:
  hub_url: 'http://localhost:4444/wd/hub'
  type: 'local' #local or remote (browser in a container)
  browser: 'chrome'
  adblock:
    enable: false
    file: 'adblock_plus-3.3.1-an+fx.xpi'

youtube:
  number_of_data_points: 10 #Collected every half a second
  agent: 'firefox'
  content_type: 'video'
  content_provider: 'youtube/1vid_test_multi_res'

flowfetch:
  enable: false
  start_url: "http://localhost:8080/start"
  stop_url: "http://localhost:8080/stop"
  video_stat_url: "http://localhost:8080/video_stat"